# Model Configuration
models:
  
  linear_regression:
    type: "LinearRegression"
    params: {}
  
  ridge:
    type: "Ridge"
    params:
      alpha: [0.1, 1.0, 10.0, 100.0]
      random_state: 42
  
  lasso:
    type: "Lasso"
    params:
      alpha: [0.1, 1.0, 10.0, 100.0]
      random_state: 42
  
  elastic_net:
    type: "ElasticNet"
    params:
      alpha: [0.1, 1.0, 10.0]
      l1_ratio: [0.1, 0.5, 0.9]
      random_state: 42
  
  random_forest:
    type: "RandomForestRegressor"
    params:
      n_estimators: [100, 200, 500]
      max_depth: [10, 20, None]
      min_samples_split: [2, 5, 10]
      random_state: 42
  
  xgboost:
    type: "XGBRegressor"
    params:
      n_estimators: [100, 200, 500]
      learning_rate: [0.01, 0.05, 0.1]
      max_depth: [3, 5, 7]
      subsample: [0.8, 0.9]
      colsample_bytree: [0.8, 0.9]
      random_state: 42
  
  lightgbm:
    type: "LGBMRegressor"
    params:
      n_estimators: [100, 200, 500]
      learning_rate: [0.01, 0.05, 0.1]
      num_leaves: [31, 50, 100]
      random_state: 42
  
  svr:
    type: "SVR"
    params:
      kernel: ["rbf", "linear"]
      C: [1, 10, 100]
      gamma: ["scale", "auto"]

# Cross-validation settings
cross_validation:
  cv_folds: 5
  scoring: "neg_mean_absolute_error"
  random_state: 42 